export const CATEGORY_LANGUAGE = {
  'Object-Oriented Programming':  { name: 'Python',     emoji: '🐍', color: '#c3e88d', bg: '#1a2e1a', border: '#27ae60' },
  'Data Structures & Algorithms': { name: 'Python',     emoji: '🐍', color: '#c3e88d', bg: '#1a2e1a', border: '#27ae60' },
  'Security':                      { name: 'Python',     emoji: '🐍', color: '#c3e88d', bg: '#1a2e1a', border: '#27ae60' },
  'Front-End':                     { name: 'JavaScript', emoji: '⚡', color: '#f7dc6f', bg: '#2e2a1a', border: '#e67e22' },
  'Back-End':                      { name: 'JavaScript', emoji: '⚡', color: '#f7dc6f', bg: '#2e2a1a', border: '#e67e22' },
};

// Client-side challenge data — code and test names only
// validate() functions live server-side only
const challenges = {
  'Object-Oriented Programming': [
    {
      id: 'oop_counter', title: 'Fix the Counter', language: 'python',
      code: [
        '# Counter Class — Fix 3 bugs', '',
        'class Counter:',
        '    def __init__(self):',
        '        self.count = 0',
        '        self.history = []', '',
        '    def increment(self):',
        '        self.count += 1',
        '        self.history.append("inc")', '',
        '    # BUG: should subtract 1, not 2',
        '    def decrement(self):',
        '        self.count -= 2',
        '        self.history.append("dec")', '',
        '    # BUG: reset does nothing',
        '    def reset(self):',
        '        pass', '',
        '    # BUG: returns history length instead of count',
        '    def value(self):',
        '        return len(self.history)',
      ],
      tests: [{ name: 'increment works' }, { name: 'decrement works' }, { name: 'reset and value work' }],
      sabotages: [
        { instruction: 'Make increment add 2 instead of 1', hint: 'Line 9' },
        { instruction: 'Make decrement increase count', hint: 'Line 14' },
        { instruction: 'Make reset set count to 999', hint: 'Line 18' },
      ],
    },
    {
      id: 'oop_bank', title: 'Fix the BankAccount', language: 'python',
      code: [
        '# BankAccount — Fix 3 bugs', '',
        'class BankAccount:',
        '    def __init__(self, owner):',
        '        self.owner = owner',
        '        self.balance = 0', '',
        '    # BUG: subtracts instead of adds',
        '    def deposit(self, amount):',
        '        self.balance -= amount', '',
        '    def withdraw(self, amount):',
        '        if amount <= self.balance:',
        '            self.balance -= amount', '',
        '    # BUG: always returns 0',
        '    def get_balance(self):',
        '        return 0',
      ],
      tests: [{ name: 'deposit adds to balance' }, { name: 'withdraw reduces balance' }, { name: 'get_balance returns balance' }],
      sabotages: [
        { instruction: 'Make deposit subtract instead of add', hint: 'Line 9' },
        { instruction: 'Make withdraw add to balance', hint: 'Line 13' },
        { instruction: 'Make get_balance always return -1', hint: 'Line 17' },
      ],
    },
    {
      id: 'oop_queue', title: 'Fix the Queue', language: 'python',
      code: [
        '# Queue — Fix 3 bugs', '',
        'class Queue:',
        '    def __init__(self):',
        '        self._data = []', '',
        '    # BUG: inserts at front instead of back',
        '    def enqueue(self, val):',
        '        self._data.insert(0, val)', '',
        '    # BUG: removes from back instead of front',
        '    def dequeue(self):',
        '        return self._data.pop() if self._data else None', '',
        '    # BUG: returns double the size',
        '    def size(self):',
        '        return len(self._data) * 2',
      ],
      tests: [{ name: 'enqueue adds to back' }, { name: 'dequeue removes from front' }, { name: 'size is correct' }],
      sabotages: [
        { instruction: 'Make enqueue insert at position 0', hint: 'Line 9' },
        { instruction: 'Make dequeue remove from the back', hint: 'Line 13' },
        { instruction: 'Make size return 0 always', hint: 'Line 17' },
      ],
    },
    {
      id: 'oop_linked', title: 'Fix the LinkedList', language: 'python',
      code: [
        '# LinkedList — Fix 3 bugs', '',
        'class Node:',
        '    def __init__(self, val):',
        '        self.val = val',
        '        self.next = None', '',
        'class LinkedList:',
        '    def __init__(self):',
        '        self.head = None',
        '        self.length = 0', '',
        '    # BUG: length never updated',
        '    def append(self, val):',
        '        node = Node(val)',
        '        if not self.head:',
        '            self.head = node',
        '        else:',
        '            cur = self.head',
        '            while cur.next:',
        '                cur = cur.next',
        '            cur.next = node', '',
        '    # BUG: always returns 0',
        '    def get_length(self):',
        '        return 0',
      ],
      tests: [{ name: 'append sets head' }, { name: 'length is updated on append' }, { name: 'get_length returns length' }],
      sabotages: [
        { instruction: 'Make append not set head', hint: 'Line 16' },
        { instruction: 'Remove length increment', hint: 'Line 14' },
        { instruction: 'Make get_length return -1', hint: 'Line 25' },
      ],
    },
  ],

  'Data Structures & Algorithms': [
    {
      id: 'dsa_bsearch', title: 'Fix Binary Search', language: 'python',
      code: [
        '# Binary Search — Fix 3 bugs', '',
        'def binary_search(arr, target):',
        '    # BUG: right should be len(arr) - 1',
        '    left, right = 0, len(arr)', '',
        '    while left <= right:',
        '        mid = (left + right) // 2',
        '        if arr[mid] == target:',
        '            return mid',
        '        elif arr[mid] < target:',
        '            # BUG: should be mid + 1',
        '            left = mid',
        '        else:',
        '            # BUG: should be mid - 1',
        '            right = mid', '',
        '    return -1',
      ],
      tests: [{ name: 'right initialized correctly' }, { name: 'left pointer advances correctly' }, { name: 'right pointer retreats correctly' }],
      sabotages: [
        { instruction: 'Change right back to len(arr)', hint: 'Line 4' },
        { instruction: 'Change left = mid + 1 to left = mid', hint: 'Line 12' },
        { instruction: 'Change right = mid - 1 to right = mid', hint: 'Line 15' },
      ],
    },
    {
      id: 'dsa_bubble', title: 'Fix Bubble Sort', language: 'python',
      code: [
        '# Bubble Sort — Fix 2 bugs', '',
        'def bubble_sort(arr):',
        '    n = len(arr)',
        '    # BUG: outer range should be range(n)',
        '    for i in range(n - 1):',
        '        for j in range(0, n - i - 1):',
        '            # BUG: should swap when arr[j] > arr[j+1]',
        '            if arr[j] < arr[j + 1]:',
        '                arr[j], arr[j + 1] = arr[j + 1], arr[j]',
        '    return arr',
      ],
      tests: [{ name: 'outer loop range correct' }, { name: 'comparison direction correct' }, { name: 'returns sorted array' }],
      sabotages: [
        { instruction: 'Change range(n) back to range(n-1)', hint: 'Line 5' },
        { instruction: 'Flip > to < in the comparison', hint: 'Line 8' },
        { instruction: 'Remove the return statement', hint: 'Line 10' },
      ],
    },
    {
      id: 'dsa_stack', title: 'Fix the Stack', language: 'python',
      code: [
        '# Stack — Fix 3 bugs', '',
        'class Stack:',
        '    def __init__(self):',
        '        self._data = []', '',
        '    # BUG: should append, not insert at 0',
        '    def push(self, val):',
        '        self._data.insert(0, val)', '',
        '    def pop(self):',
        '        return self._data.pop() if self._data else None', '',
        '    # BUG: should return last item, not first',
        '    def peek(self):',
        '        return self._data[0] if self._data else None', '',
        '    # BUG: returns double',
        '    def size(self):',
        '        return len(self._data) * 2',
      ],
      tests: [{ name: 'push appends correctly' }, { name: 'peek returns last item' }, { name: 'size is correct' }],
      sabotages: [
        { instruction: 'Change append back to insert(0, val)', hint: 'Line 8' },
        { instruction: 'Change peek to return index 0', hint: 'Line 15' },
        { instruction: 'Make size return 0', hint: 'Line 19' },
      ],
    },
    {
      id: 'dsa_fib', title: 'Fix Fibonacci', language: 'python',
      code: [
        '# Fibonacci — Fix 3 bugs', '',
        'def fibonacci(n):',
        '    if n <= 0:',
        '        return 0',
        '    # BUG: should return 1',
        '    if n == 1:',
        '        return 0', '',
        '    # BUG: a and b swapped',
        '    a, b = 1, 0', '',
        '    for _ in range(2, n):',
        '        a, b = a + b, a', '',
        '    return b',
      ],
      tests: [{ name: 'fib(1) returns 1' }, { name: 'a, b initialized correctly' }, { name: 'returns correct value' }],
      sabotages: [
        { instruction: 'Make fib(1) return 0 again', hint: 'Line 7' },
        { instruction: 'Swap a and b back to 1, 0', hint: 'Line 10' },
        { instruction: 'Make it return a instead of b', hint: 'Line 15' },
      ],
    },
  ],

  'Security': [
    {
      id: 'sec_auth', title: 'Fix Auth Module', language: 'python',
      code: [
        '# Auth Module — Fix 3 bugs', '',
        'class Auth:',
        '    def __init__(self):',
        '        self.users = {}',
        '        self.sessions = {}', '',
        '    # BUG: always returns True regardless of credentials',
        '    def login(self, username, password):',
        '        return True', '',
        '    # BUG: does nothing',
        '    def logout(self, token):',
        '        pass', '',
        '    # BUG: always returns True',
        '    def is_admin(self, username):',
        '        return True',
      ],
      tests: [{ name: 'login checks credentials' }, { name: 'logout removes session' }, { name: 'is_admin checks role' }],
      sabotages: [
        { instruction: 'Make login always return True', hint: 'Line 9' },
        { instruction: 'Make logout do nothing (pass)', hint: 'Line 13' },
        { instruction: 'Make is_admin always return True', hint: 'Line 17' },
      ],
    },
    {
      id: 'sec_hash', title: 'Fix Password Hasher', language: 'python',
      code: [
        '# Password Hasher — Fix 3 bugs', '',
        'import hashlib', '',
        'class Hasher:',
        '    # BUG: uses weak MD5, should use sha256',
        '    def hash_password(self, password):',
        '        return hashlib.md5(password.encode()).hexdigest()', '',
        '    # BUG: always returns True',
        '    def verify(self, password, hashed):',
        '        return True', '',
        '    # BUG: always returns True',
        '    def is_strong(self, password):',
        '        return True',
      ],
      tests: [{ name: 'uses sha256 not md5' }, { name: 'verify actually checks hash' }, { name: 'is_strong validates length' }],
      sabotages: [
        { instruction: 'Change sha256 back to md5', hint: 'Line 7' },
        { instruction: 'Make verify always return True', hint: 'Line 11' },
        { instruction: 'Make is_strong always return True', hint: 'Line 15' },
      ],
    },
    {
      id: 'sec_sanitize', title: 'Fix Input Sanitizer', language: 'python',
      code: [
        '# Input Sanitizer — Fix 3 bugs', '',
        'import re', '',
        'class Sanitizer:',
        '    # BUG: returns input unchanged',
        '    def sanitize(self, text):',
        '        return text', '',
        '    # BUG: always returns True',
        '    def is_email(self, text):',
        '        return True', '',
        '    # BUG: returns html unchanged',
        '    def strip_tags(self, html):',
        '        return html',
      ],
      tests: [{ name: 'sanitize removes special chars' }, { name: 'is_email uses regex' }, { name: 'strip_tags removes html' }],
      sabotages: [
        { instruction: 'Make sanitize return text unchanged', hint: 'Line 7' },
        { instruction: 'Make is_email always return True', hint: 'Line 11' },
        { instruction: 'Make strip_tags return html unchanged', hint: 'Line 15' },
      ],
    },
    {
      id: 'sec_ratelimit', title: 'Fix Rate Limiter', language: 'python',
      code: [
        '# Rate Limiter — Fix 3 bugs', '',
        'import time', '',
        'class RateLimiter:',
        '    def __init__(self, max_calls, period):',
        '        self.max_calls = max_calls',
        '        self.period = period',
        '        self.calls = {}', '',
        '    # BUG: always returns True',
        '    def is_allowed(self, user_id):',
        '        return True', '',
        '    # BUG: does nothing',
        '    def reset(self, user_id):',
        '        pass', '',
        '    # BUG: always returns 0',
        '    def count(self, user_id):',
        '        return 0',
      ],
      tests: [{ name: 'is_allowed checks call count' }, { name: 'reset clears user data' }, { name: 'count returns actual count' }],
      sabotages: [
        { instruction: 'Make is_allowed always return True', hint: 'Line 12' },
        { instruction: 'Make reset do nothing (pass)', hint: 'Line 16' },
        { instruction: 'Make count always return 0', hint: 'Line 20' },
      ],
    },
  ],

  'Front-End': [
    {
      id: 'fe_dom', title: 'Fix DOM Manager', language: 'javascript',
      code: [
        '// DOM Manager — Fix 3 bugs', '',
        'class DOMManager {',
        '  // BUG: always returns null',
        '  createElement(tag, text) {',
        '    return null;',
        '  }', '',
        '  // BUG: does nothing',
        '  addClass(el, cls) {',
        '    // missing implementation',
        '  }', '',
        '  // BUG: overwrites all styles',
        '  setStyle(el, prop, val) {',
        '    el.style = val;',
        '  }',
        '}',
      ],
      tests: [{ name: 'createElement creates element' }, { name: 'addClass uses classList' }, { name: 'setStyle sets property correctly' }],
      sabotages: [
        { instruction: 'Make createElement return null', hint: 'Line 5' },
        { instruction: 'Remove classList.add call', hint: 'Line 10' },
        { instruction: 'Make setStyle overwrite el.style directly', hint: 'Line 15' },
      ],
    },
    {
      id: 'fe_state', title: 'Fix State Manager', language: 'javascript',
      code: [
        '// State Manager — Fix 3 bugs', '',
        'class Store {',
        '  constructor(initial) {',
        '    this.state = initial;',
        '    this.listeners = [];',
        '  }', '',
        '  // BUG: returns undefined instead of state',
        '  getState() {',
        '    return undefined;',
        '  }', '',
        '  // BUG: replaces state instead of merging',
        '  setState(patch) {',
        '    this.state = patch;',
        '  }', '',
        '  // BUG: stores listener but never calls it',
        '  subscribe(fn) {',
        '    this.listeners.push(fn);',
        '  }',
        '}',
      ],
      tests: [{ name: 'getState returns this.state' }, { name: 'setState merges with spread' }, { name: 'subscribe notifies listeners' }],
      sabotages: [
        { instruction: 'Make getState return undefined', hint: 'Line 10' },
        { instruction: 'Remove spread operator from setState', hint: 'Line 15' },
        { instruction: 'Remove the forEach notification call', hint: 'Line 20' },
      ],
    },
    {
      id: 'fe_router', title: 'Fix Mini Router', language: 'javascript',
      code: [
        '// Mini Router — Fix 3 bugs', '',
        'class Router {',
        '  constructor() {',
        '    this.routes = {};',
        '    this.current = "/";',
        '  }', '',
        '  // BUG: does not save the route',
        '  register(path, handler) {',
        '    // missing',
        '  }', '',
        '  // BUG: does not update current path',
        '  navigate(path) {',
        '    // missing',
        '  }', '',
        '  // BUG: returns null instead of current',
        '  getCurrent() {',
        '    return null;',
        '  }',
        '}',
      ],
      tests: [{ name: 'register saves the route' }, { name: 'navigate updates current' }, { name: 'getCurrent returns current path' }],
      sabotages: [
        { instruction: 'Remove the route assignment', hint: 'Line 10' },
        { instruction: 'Remove this.current = path', hint: 'Line 15' },
        { instruction: 'Make getCurrent return null', hint: 'Line 20' },
      ],
    },
    {
      id: 'fe_validator', title: 'Fix Form Validator', language: 'javascript',
      code: [
        '// Form Validator — Fix 3 bugs', '',
        'class Validator {',
        '  // BUG: always returns true',
        '  required(val) {',
        '    return true;',
        '  }', '',
        '  // BUG: always returns true',
        '  minLength(val, min) {',
        '    return true;',
        '  }', '',
        '  // BUG: always returns true',
        '  isEmail(val) {',
        '    return true;',
        '  }',
        '}',
      ],
      tests: [{ name: 'required checks for empty value' }, { name: 'minLength checks length' }, { name: 'isEmail validates format' }],
      sabotages: [
        { instruction: 'Make required always return true', hint: 'Line 5' },
        { instruction: 'Make minLength always return true', hint: 'Line 10' },
        { instruction: 'Make isEmail always return true', hint: 'Line 15' },
      ],
    },
  ],

  'Back-End': [
    {
      id: 'be_middleware', title: 'Fix Express Middleware', language: 'javascript',
      code: [
        '// Express Middleware — Fix 3 bugs', '',
        'const logger = (req, res, next) => {',
        '  console.log(req.method, req.url);',
        '  // BUG: never calls next()',
        '};', '',
        'const auth = (req, res, next) => {',
        '  const token = req.headers.authorization;',
        '  // BUG: blocks all requests even with valid token',
        '  res.status(401).json({ error: "Unauthorized" });',
        '};', '',
        'const errorHandler = (err, req, res, next) => {',
        '  console.error(err);',
        '  // BUG: never sends a response',
        '};',
      ],
      tests: [{ name: 'logger calls next()' }, { name: 'auth checks token before blocking' }, { name: 'errorHandler sends response' }],
      sabotages: [
        { instruction: 'Remove next() from logger', hint: 'Line 4' },
        { instruction: 'Make auth block all requests', hint: 'Line 10' },
        { instruction: 'Remove res.status from errorHandler', hint: 'Line 15' },
      ],
    },
    {
      id: 'be_db', title: 'Fix DB Query Builder', language: 'javascript',
      code: [
        '// Query Builder — Fix 3 bugs', '',
        'class QueryBuilder {',
        '  constructor() {',
        '    this.query = "";',
        '  }', '',
        '  // BUG: uses += so query accumulates across calls',
        '  select(table) {',
        '    this.query += `SELECT * FROM ${table}`;',
        '    return this;',
        '  }', '',
        '  // BUG: does not add WHERE condition',
        '  where(condition) {',
        '    return this;',
        '  }', '',
        '  // BUG: returns empty string',
        '  build() {',
        '    return "";',
        '  }',
        '}',
      ],
      tests: [{ name: 'select assigns not appends' }, { name: 'where adds condition' }, { name: 'build returns the query' }],
      sabotages: [
        { instruction: 'Change = to += in select', hint: 'Line 9' },
        { instruction: 'Remove the WHERE clause from where()', hint: 'Line 15' },
        { instruction: 'Make build() return empty string', hint: 'Line 20' },
      ],
    },
    {
      id: 'be_cache', title: 'Fix Cache Layer', language: 'javascript',
      code: [
        '// Cache Layer — Fix 3 bugs', '',
        'class Cache {',
        '  constructor(ttl) {',
        '    this.ttl = ttl;',
        '    this.store = {};',
        '    this.timestamps = {};',
        '  }', '',
        '  // BUG: saves timestamp but not the value',
        '  set(key, value) {',
        '    this.timestamps[key] = Date.now();',
        '  }', '',
        '  // BUG: always returns undefined',
        '  get(key) {',
        '    return undefined;',
        '  }', '',
        '  // BUG: always returns false',
        '  has(key) {',
        '    return false;',
        '  }',
        '}',
      ],
      tests: [{ name: 'set stores the value' }, { name: 'get retrieves the value' }, { name: 'has checks store correctly' }],
      sabotages: [
        { instruction: 'Remove this.store[key] = value', hint: 'Line 11' },
        { instruction: 'Make get() return undefined', hint: 'Line 16' },
        { instruction: 'Make has() return false', hint: 'Line 21' },
      ],
    },
    {
      id: 'be_api', title: 'Fix API Response Helper', language: 'javascript',
      code: [
        '// API Response Helper — Fix 3 bugs', '',
        'class ApiResponse {',
        '  // BUG: sends 500 instead of 200',
        '  success(res, data) {',
        '    res.status(500).json(data);',
        '  }', '',
        '  // BUG: always sends 200 instead of error code',
        '  error(res, message, code = 400) {',
        '    res.status(200).json({ error: message });',
        '  }', '',
        '  // BUG: ignores page and limit',
        '  paginate(res, items, page, limit) {',
        '    res.json({ items });',
        '  }',
        '}',
      ],
      tests: [{ name: 'success sends 200' }, { name: 'error uses the code parameter' }, { name: 'paginate slices items' }],
      sabotages: [
        { instruction: 'Change 200 to 500 in success()', hint: 'Line 5' },
        { instruction: 'Make error() always use status 200', hint: 'Line 10' },
        { instruction: 'Remove slice from paginate()', hint: 'Line 15' },
      ],
    },
  ],
};

export function getChallengesForCategory(category) {
  return challenges[category] || challenges['Object-Oriented Programming'];
}

export function getChallengeForRound(category, round) {
  const list = getChallengesForCategory(category);
  return list[(round - 1) % list.length];
}