/**
 * Code challenge bank.
 * Each challenge has:
 *   - id, title
 *   - code: plain text lines (array) shown in editor
 *   - tests: { name, assertCode } — assertCode is eval'd server-side
 *   - sabotages: { instruction, hint, badLineIndex, badCode }
 */

const challenges = {
  'Object-Oriented Programming': [
    {
      id: 'oop_counter',
      title: 'Fix the Counter',
      code: [
        '# Counter Class — Fix 3 TODOs',
        '',
        'class Counter:',
        '    def __init__(self):',
        '        self.count = 0',
        '        self.history = []',
        '',
        '    def increment(self):',
        '        self.count += 1',
        '        self.history.append("inc")',
        '',
        '    # TODO: Fix decrement() — should subtract 1, not 2',
        '    def decrement(self):',
        '        self.count -= 2',
        '        self.history.append("dec")',
        '',
        '    # TODO: Implement reset()',
        '    def reset(self):',
        '        pass',
        '',
        '    # TODO: Fix value() — returns history length, not count',
        '    def value(self):',
        '        return len(self.history)',
      ],
      tests: [
        { name: 'increment works' },
        { name: 'decrement works' },
        { name: 'reset works' },
      ],
      sabotages: [
        { instruction: 'Make increment add 2', hint: 'Line 9', badLineIndex: 8 },
        { instruction: 'Make decrement increase count', hint: 'Line 14', badLineIndex: 13 },
        { instruction: 'Make reset set count to 100', hint: 'Line 18', badLineIndex: 17 },
      ],
    },
    {
      id: 'oop_bank',
      title: 'Fix the BankAccount',
      code: [
        '# BankAccount — Fix 3 TODOs',
        '',
        'class BankAccount:',
        '    def __init__(self, owner):',
        '        self.owner = owner',
        '        self.balance = 0',
        '',
        '    # TODO: deposit adds negative',
        '    def deposit(self, amount):',
        '        self.balance -= amount',
        '',
        '    # TODO: withdraw never checks balance',
        '    def withdraw(self, amount):',
        '        self.balance -= amount',
        '',
        '    # TODO: get_balance returns 0',
        '    def get_balance(self):',
        '        return 0',
      ],
      tests: [
        { name: 'deposit works' },
        { name: 'withdraw works' },
        { name: 'balance correct' },
      ],
      sabotages: [
        { instruction: 'Make deposit subtract instead of add', hint: 'Line 10', badLineIndex: 9 },
        { instruction: 'Make withdraw add to balance', hint: 'Line 14', badLineIndex: 13 },
        { instruction: 'Always return -1 from get_balance', hint: 'Line 18', badLineIndex: 17 },
      ],
    },
    {
      id: 'oop_queue',
      title: 'Fix the Queue',
      code: [
        '# Queue — Fix 3 TODOs',
        '',
        'class Queue:',
        '    def __init__(self):',
        '        self._data = []',
        '',
        '    # TODO: enqueue inserts at wrong position',
        '    def enqueue(self, val):',
        '        self._data.insert(0, val)',
        '',
        '    # TODO: dequeue removes last instead of first',
        '    def dequeue(self):',
        '        return self._data.pop() if self._data else None',
        '',
        '    # TODO: size returns double',
        '    def size(self):',
        '        return len(self._data) * 2',
      ],
      tests: [
        { name: 'enqueue works' },
        { name: 'dequeue works' },
        { name: 'size correct' },
      ],
      sabotages: [
        { instruction: 'Make enqueue insert at end', hint: 'Line 9', badLineIndex: 8 },
        { instruction: 'Make dequeue remove first instead', hint: 'Line 13', badLineIndex: 12 },
        { instruction: 'Make size always return 0', hint: 'Line 17', badLineIndex: 16 },
      ],
    },
    {
      id: 'oop_linked',
      title: 'Fix the LinkedList',
      code: [
        '# LinkedList Node — Fix 3 TODOs',
        '',
        'class Node:',
        '    def __init__(self, val):',
        '        self.val = val',
        '        self.next = None',
        '',
        'class LinkedList:',
        '    def __init__(self):',
        '        self.head = None',
        '        self.length = 0',
        '',
        '    # TODO: append does not update length',
        '    def append(self, val):',
        '        node = Node(val)',
        '        if not self.head:',
        '            self.head = node',
        '        else:',
        '            cur = self.head',
        '            while cur.next: cur = cur.next',
        '            cur.next = node',
        '',
        '    # TODO: get_length returns 0',
        '    def get_length(self):',
        '        return 0',
      ],
      tests: [
        { name: 'append works' },
        { name: 'length tracks' },
        { name: 'head is set' },
      ],
      sabotages: [
        { instruction: 'Make append not update head', hint: 'Line 17', badLineIndex: 16 },
        { instruction: 'Make length always -1', hint: 'Line 25', badLineIndex: 24 },
        { instruction: 'Make append clear next pointer', hint: 'Line 21', badLineIndex: 20 },
      ],
    },
  ],

  'Data Structures & Algorithms': [
    {
      id: 'dsa_bsearch',
      title: 'Fix Binary Search',
      code: [
        '# Binary Search — Fix 3 bugs',
        '',
        'def binary_search(arr, target):',
        '    left, right = 0, len(arr)',
        '',
        '    # TODO: right init should be len(arr)-1',
        '    while left <= right:',
        '        mid = (left + right) // 2',
        '        if arr[mid] == target:',
        '            return mid',
        '        elif arr[mid] < target:',
        '            # TODO: left = mid+1, not mid',
        '            left = mid',
        '        else:',
        '            # TODO: right = mid-1, not mid',
        '            right = mid',
        '',
        '    return -1',
      ],
      tests: [
        { name: 'finds element' },
        { name: 'handles edges' },
        { name: 'returns -1 if missing' },
      ],
      sabotages: [
        { instruction: 'Make loop condition use < instead of <=', hint: 'Line 7', badLineIndex: 6 },
        { instruction: 'Make mid always 0', hint: 'Line 8', badLineIndex: 7 },
        { instruction: 'Make return always -1', hint: 'Line 10', badLineIndex: 9 },
      ],
    },
    {
      id: 'dsa_bubble',
      title: 'Fix Bubble Sort',
      code: [
        '# Bubble Sort — Fix 3 bugs',
        '',
        'def bubble_sort(arr):',
        '    n = len(arr)',
        '    # TODO: outer range wrong — should be range(n)',
        '    for i in range(n - 1):',
        '        for j in range(0, n - i - 1):',
        '            # TODO: comparison reversed',
        '            if arr[j] > arr[j + 1]:',
        '                arr[j], arr[j + 1] = arr[j + 1], arr[j]',
        '    return arr',
      ],
      tests: [
        { name: 'sorts ascending' },
        { name: 'handles duplicates' },
        { name: 'returns array' },
      ],
      sabotages: [
        { instruction: 'Make outer loop range(1) only', hint: 'Line 5', badLineIndex: 4 },
        { instruction: 'Reverse the swap', hint: 'Line 10', badLineIndex: 9 },
        { instruction: 'Skip the inner loop', hint: 'Line 7', badLineIndex: 6 },
      ],
    },
    {
      id: 'dsa_stack',
      title: 'Fix the Stack',
      code: [
        '# Stack — Fix 3 bugs',
        '',
        'class Stack:',
        '    def __init__(self):',
        '        self._data = []',
        '',
        '    # TODO: push inserts at 0 instead of appending',
        '    def push(self, val):',
        '        self._data.insert(0, val)',
        '',
        '    def pop(self):',
        '        return self._data.pop() if self._data else None',
        '',
        '    # TODO: peek returns index 0 not last',
        '    def peek(self):',
        '        return self._data[0]',
        '',
        '    # TODO: size returns double',
        '    def size(self):',
        '        return len(self._data) * 2',
      ],
      tests: [
        { name: 'push works' },
        { name: 'peek works' },
        { name: 'size correct' },
      ],
      sabotages: [
        { instruction: 'Make push clear the stack', hint: 'Line 9', badLineIndex: 8 },
        { instruction: 'Make peek always None', hint: 'Line 16', badLineIndex: 15 },
        { instruction: 'Make size always 0', hint: 'Line 20', badLineIndex: 19 },
      ],
    },
    {
      id: 'dsa_fib',
      title: 'Fix Fibonacci',
      code: [
        '# Fibonacci — Fix 3 bugs',
        '',
        'def fibonacci(n):',
        '    if n <= 0: return 0',
        '    # TODO: base case for 1 returns 0',
        '    if n == 1: return 0',
        '',
        '    # TODO: a and b initialized wrong',
        '    a, b = 1, 0',
        '',
        '    for _ in range(2, n):',
        '        # TODO: update step wrong',
        '        a, b = a + b, a',
        '',
        '    return b',
      ],
      tests: [
        { name: 'fib(1) == 1' },
        { name: 'fib(5) == 5' },
        { name: 'fib(10) == 55' },
      ],
      sabotages: [
        { instruction: 'Make fib(1) return -1', hint: 'Line 6', badLineIndex: 5 },
        { instruction: 'Swap a and b init to 0,1', hint: 'Line 9', badLineIndex: 8 },
        { instruction: 'Make loop skip every other', hint: 'Line 11', badLineIndex: 10 },
      ],
    },
  ],

  Security: [
    {
      id: 'sec_auth',
      title: 'Fix Auth Module',
      code: [
        '# Auth Module — Fix 3 security bugs',
        '',
        'class Auth:',
        '    def __init__(self):',
        '        self.users = {}',
        '        self.sessions = {}',
        '',
        '    # TODO: login always returns True',
        '    def login(self, username, password):',
        '        return True',
        '',
        '    # TODO: logout does nothing',
        '    def logout(self, token):',
        '        pass',
        '',
        '    # TODO: is_admin always True',
        '    def is_admin(self, username):',
        '        return True',
      ],
      tests: [
        { name: 'login validates' },
        { name: 'logout removes session' },
        { name: 'is_admin checks role' },
      ],
      sabotages: [
        { instruction: 'Make login always False', hint: 'Line 10', badLineIndex: 9 },
        { instruction: 'Make logout corrupt sessions', hint: 'Line 14', badLineIndex: 13 },
        { instruction: 'Make is_admin always False', hint: 'Line 18', badLineIndex: 17 },
      ],
    },
    {
      id: 'sec_hash',
      title: 'Fix Password Hasher',
      code: [
        '# Password Hasher — Fix 3 bugs',
        '',
        'import hashlib',
        '',
        'class Hasher:',
        '    # TODO: no salt used',
        '    def hash_password(self, password):',
        '        return hashlib.md5(password.encode()).hexdigest()',
        '',
        '    # TODO: verify always True',
        '    def verify(self, password, hashed):',
        '        return True',
        '',
        '    # TODO: strength check always passes',
        '    def is_strong(self, password):',
        '        return True',
      ],
      tests: [
        { name: 'hash produces output' },
        { name: 'verify checks correctly' },
        { name: 'strength validates' },
      ],
      sabotages: [
        { instruction: 'Make hash return empty string', hint: 'Line 8', badLineIndex: 7 },
        { instruction: 'Make verify always False', hint: 'Line 12', badLineIndex: 11 },
        { instruction: 'Make is_strong always False', hint: 'Line 16', badLineIndex: 15 },
      ],
    },
    {
      id: 'sec_sanitize',
      title: 'Fix Input Sanitizer',
      code: [
        '# Input Sanitizer — Fix 3 bugs',
        '',
        'import re',
        '',
        'class Sanitizer:',
        '    # TODO: sanitize returns input unchanged',
        '    def sanitize(self, text):',
        '        return text',
        '',
        '    # TODO: is_email always True',
        '    def is_email(self, text):',
        '        return True',
        '',
        '    # TODO: strip_tags does nothing',
        '    def strip_tags(self, html):',
        '        return html',
      ],
      tests: [
        { name: 'sanitize strips html' },
        { name: 'email validation works' },
        { name: 'strip_tags works' },
      ],
      sabotages: [
        { instruction: 'Make sanitize double input', hint: 'Line 8', badLineIndex: 7 },
        { instruction: 'Make is_email always False', hint: 'Line 12', badLineIndex: 11 },
        { instruction: 'Make strip_tags add script tag', hint: 'Line 16', badLineIndex: 15 },
      ],
    },
    {
      id: 'sec_ratelimit',
      title: 'Fix Rate Limiter',
      code: [
        '# Rate Limiter — Fix 3 bugs',
        '',
        'import time',
        '',
        'class RateLimiter:',
        '    def __init__(self, max_calls, period):',
        '        self.max_calls = max_calls',
        '        self.period = period',
        '        self.calls = {}',
        '',
        '    # TODO: is_allowed always True',
        '    def is_allowed(self, user_id):',
        '        return True',
        '',
        '    # TODO: reset does not clear user',
        '    def reset(self, user_id):',
        '        pass',
        '',
        '    # TODO: count always returns 0',
        '    def count(self, user_id):',
        '        return 0',
      ],
      tests: [
        { name: 'allows under limit' },
        { name: 'blocks over limit' },
        { name: 'count tracks calls' },
      ],
      sabotages: [
        { instruction: 'Make is_allowed always False', hint: 'Line 13', badLineIndex: 12 },
        { instruction: 'Make reset corrupt all users', hint: 'Line 16', badLineIndex: 15 },
        { instruction: 'Make count always return 999', hint: 'Line 21', badLineIndex: 20 },
      ],
    },
  ],

  'Front-End': [
    {
      id: 'fe_dom',
      title: 'Fix DOM Manager',
      code: [
        '// DOM Manager — Fix 3 TODOs',
        '',
        'class DOMManager {',
        '  // TODO: createElement returns null',
        '  createElement(tag, text) {',
        '    return null;',
        '  }',
        '',
        '  // TODO: addClass does nothing',
        '  addClass(el, cls) {',
        '    // missing implementation',
        '  }',
        '',
        '  // TODO: setStyle overwrites all styles',
        '  setStyle(el, prop, val) {',
        '    el.style = val;',
        '  }',
        '}',
      ],
      tests: [
        { name: 'createElement works' },
        { name: 'addClass adds class' },
        { name: 'setStyle sets property' },
      ],
      sabotages: [
        { instruction: 'Make createElement throw an error', hint: 'Line 6', badLineIndex: 5 },
        { instruction: 'Make addClass remove the class', hint: 'Line 11', badLineIndex: 10 },
        { instruction: 'Make setStyle clear all styles', hint: 'Line 16', badLineIndex: 15 },
      ],
    },
    {
      id: 'fe_state',
      title: 'Fix State Manager',
      code: [
        '// Mini State Manager — Fix 3 TODOs',
        '',
        'class Store {',
        '  constructor(initial) {',
        '    this.state = initial;',
        '    this.listeners = [];',
        '  }',
        '',
        '  // TODO: getState returns undefined',
        '  getState() {',
        '    return undefined;',
        '  }',
        '',
        '  // TODO: setState does not merge',
        '  setState(patch) {',
        '    this.state = patch;',
        '  }',
        '',
        '  // TODO: subscribe never calls listener',
        '  subscribe(fn) {',
        '    this.listeners.push(fn);',
        '  }',
        '}',
      ],
      tests: [
        { name: 'getState returns state' },
        { name: 'setState merges' },
        { name: 'subscribe notifies' },
      ],
      sabotages: [
        { instruction: 'Make getState return null', hint: 'Line 11', badLineIndex: 10 },
        { instruction: 'Make setState clear all state', hint: 'Line 16', badLineIndex: 15 },
        { instruction: 'Make subscribe remove listeners', hint: 'Line 21', badLineIndex: 20 },
      ],
    },
    {
      id: 'fe_router',
      title: 'Fix Mini Router',
      code: [
        '// Mini Router — Fix 3 TODOs',
        '',
        'class Router {',
        '  constructor() {',
        '    this.routes = {};',
        '    this.current = "/";',
        '  }',
        '',
        '  // TODO: register does not save route',
        '  register(path, handler) {',
        '    // missing',
        '  }',
        '',
        '  // TODO: navigate does not update current',
        '  navigate(path) {',
        '    // missing',
        '  }',
        '',
        '  // TODO: getCurrent returns null',
        '  getCurrent() {',
        '    return null;',
        '  }',
        '}',
      ],
      tests: [
        { name: 'register saves route' },
        { name: 'navigate updates path' },
        { name: 'getCurrent is correct' },
      ],
      sabotages: [
        { instruction: 'Make register delete route', hint: 'Line 11', badLineIndex: 10 },
        { instruction: 'Make navigate always go to "/"', hint: 'Line 16', badLineIndex: 15 },
        { instruction: 'Make getCurrent return "/"', hint: 'Line 21', badLineIndex: 20 },
      ],
    },
    {
      id: 'fe_validator',
      title: 'Fix Form Validator',
      code: [
        '// Form Validator — Fix 3 TODOs',
        '',
        'class Validator {',
        '  // TODO: required always passes',
        '  required(val) {',
        '    return true;',
        '  }',
        '',
        '  // TODO: minLength always passes',
        '  minLength(val, min) {',
        '    return true;',
        '  }',
        '',
        '  // TODO: isEmail always passes',
        '  isEmail(val) {',
        '    return true;',
        '  }',
        '}',
      ],
      tests: [
        { name: 'required catches empty' },
        { name: 'minLength checks length' },
        { name: 'isEmail validates format' },
      ],
      sabotages: [
        { instruction: 'Make required always fail', hint: 'Line 6', badLineIndex: 5 },
        { instruction: 'Make minLength always fail', hint: 'Line 11', badLineIndex: 10 },
        { instruction: 'Make isEmail always fail', hint: 'Line 16', badLineIndex: 15 },
      ],
    },
  ],

  'Back-End': [
    {
      id: 'be_middleware',
      title: 'Fix Express Middleware',
      code: [
        '// Express Middleware — Fix 3 TODOs',
        '',
        'const logger = (req, res, next) => {',
        '  // TODO: never calls next()',
        '  console.log(req.method, req.url);',
        '};',
        '',
        'const auth = (req, res, next) => {',
        '  const token = req.headers.authorization;',
        '  // TODO: always blocks even with valid token',
        '  res.status(401).json({ error: "Unauthorized" });',
        '};',
        '',
        'const errorHandler = (err, req, res, next) => {',
        '  // TODO: does not send response',
        '  console.error(err);',
        '};',
      ],
      tests: [
        { name: 'logger calls next' },
        { name: 'auth allows valid token' },
        { name: 'errorHandler responds' },
      ],
      sabotages: [
        { instruction: 'Make logger throw an error', hint: 'Line 5', badLineIndex: 4 },
        { instruction: 'Make auth always pass (no check)', hint: 'Line 11', badLineIndex: 10 },
        { instruction: 'Make errorHandler send 200', hint: 'Line 16', badLineIndex: 15 },
      ],
    },
    {
      id: 'be_db',
      title: 'Fix DB Query Builder',
      code: [
        '// Query Builder — Fix 3 TODOs',
        '',
        'class QueryBuilder {',
        '  constructor() { this.query = ""; }',
        '',
        '  // TODO: select overwrites query instead of setting it',
        '  select(table) {',
        '    this.query += `SELECT * FROM ${table}`;',
        '    return this;',
        '  }',
        '',
        '  // TODO: where does not add condition',
        '  where(condition) {',
        '    return this;',
        '  }',
        '',
        '  // TODO: build returns empty string',
        '  build() {',
        '    return "";',
        '  }',
        '}',
      ],
      tests: [
        { name: 'select builds query' },
        { name: 'where adds condition' },
        { name: 'build returns query' },
      ],
      sabotages: [
        { instruction: 'Make select corrupt query', hint: 'Line 8', badLineIndex: 7 },
        { instruction: 'Make where clear the query', hint: 'Line 14', badLineIndex: 13 },
        { instruction: 'Make build return "DROP TABLE users"', hint: 'Line 19', badLineIndex: 18 },
      ],
    },
    {
      id: 'be_cache',
      title: 'Fix Cache Layer',
      code: [
        '// Cache Layer — Fix 3 TODOs',
        '',
        'class Cache {',
        '  constructor(ttl) {',
        '    this.ttl = ttl;',
        '    this.store = {};',
        '    this.timestamps = {};',
        '  }',
        '',
        '  // TODO: set does not store value',
        '  set(key, value) {',
        '    this.timestamps[key] = Date.now();',
        '  }',
        '',
        '  // TODO: get never returns value',
        '  get(key) {',
        '    return undefined;',
        '  }',
        '',
        '  // TODO: has always returns false',
        '  has(key) {',
        '    return false;',
        '  }',
        '}',
      ],
      tests: [
        { name: 'set stores value' },
        { name: 'get retrieves value' },
        { name: 'has returns true' },
      ],
      sabotages: [
        { instruction: 'Make set delete the key', hint: 'Line 12', badLineIndex: 11 },
        { instruction: 'Make get always return null', hint: 'Line 17', badLineIndex: 16 },
        { instruction: 'Make has always return true', hint: 'Line 22', badLineIndex: 21 },
      ],
    },
    {
      id: 'be_api',
      title: 'Fix API Response Helper',
      code: [
        '// API Response Helper — Fix 3 TODOs',
        '',
        'class ApiResponse {',
        '  // TODO: success always sends 500',
        '  success(res, data) {',
        '    res.status(500).json(data);',
        '  }',
        '',
        '  // TODO: error always sends 200',
        '  error(res, message, code = 400) {',
        '    res.status(200).json({ error: message });',
        '  }',
        '',
        '  // TODO: paginate ignores page/limit',
        '  paginate(res, items, page, limit) {',
        '    res.json({ items });',
        '  }',
        '}',
      ],
      tests: [
        { name: 'success sends 200' },
        { name: 'error sends correct code' },
        { name: 'paginate slices items' },
      ],
      sabotages: [
        { instruction: 'Make success send 418', hint: 'Line 6', badLineIndex: 5 },
        { instruction: 'Make error send 500 always', hint: 'Line 11', badLineIndex: 10 },
        { instruction: 'Make paginate return empty array', hint: 'Line 16', badLineIndex: 15 },
      ],
    },
  ],
};

function getChallengesForCategory(category) {
  return challenges[category] || challenges['Object-Oriented Programming'];
}

function getChallengeForRound(category, round) {
  const list = getChallengesForCategory(category);
  return list[(round - 1) % list.length];
}

module.exports = { challenges, getChallengesForCategory, getChallengeForRound };
