/**
 * Each challenge is a single coherent file split into 3 sections.
 * Players work on the entire file throughout the game.
 * Tests accumulate — passing a test keeps it green forever.
 * The impostor's goal is to make a passing test fail again.
 *
 * Structure:
 *   code[]         — plain text lines, NO HTML
 *   sections[]     — { title, startLine, endLine }
 *   tests[]        — 9 total (3 per section), each with validate(lines)
 *   impostorGoals  — description of what the impostor should try to do
 */

const challenges = {

  'Object-Oriented Programming': {
    id: 'oop_bank_system',
    title: 'Banking System',
    language: 'python',
    description: 'A banking system with accounts, transactions, and validation.',
    impostorGoals: [
      'Flip a comparison sign in validate_amount (> to >=)',
      'Change withdrawal logic to add instead of subtract',
      'Make get_balance return self.balance + 1',
    ],
    sections: [
      { title: 'Account Creation & Validation', startLine: 0, endLine: 24 },
      { title: 'Deposits & Withdrawals', startLine: 25, endLine: 50 },
      { title: 'Transaction History', startLine: 51, endLine: 75 },
    ],
    code: [
      '# Banking System — Fix all bugs across 3 sections',
      '# Work together to pass all 9 tests',
      '',
      '# ═══ SECTION 1: Account Creation & Validation ═══',
      '',
      'class BankAccount:',
      '    def __init__(self, owner, initial_balance=0):',
      '        self.owner = owner',
      '        self.balance = initial_balance',
      '        self.transactions = []',
      '        self.active = True',
      '',
      '    # BUG: should reject negative amounts (use > not >=)',
      '    def validate_amount(self, amount):',
      '        if amount >= 0:',
      '            raise ValueError("Amount must be positive")',
      '        return True',
      '',
      '    # BUG: should return False when not active, not raise',
      '    def is_active(self):',
      '        if not self.active:',
      '            raise RuntimeError("Account is closed")',
      '        return True',
      '',
      '    def close_account(self):',
      '        self.active = False',
      '',
      '# ═══ SECTION 2: Deposits & Withdrawals ═══',
      '',
      '    # BUG: subtracts instead of adds on deposit',
      '    def deposit(self, amount):',
      '        self.validate_amount(amount)',
      '        if not self.is_active():',
      '            return False',
      '        self.balance -= amount',
      '        self.transactions.append(("deposit", amount))',
      '        return True',
      '',
      '    # BUG: does not check sufficient funds',
      '    def withdraw(self, amount):',
      '        self.validate_amount(amount)',
      '        if not self.is_active():',
      '            return False',
      '        self.balance -= amount',
      '        self.transactions.append(("withdraw", amount))',
      '        return True',
      '',
      '    # BUG: returns balance + 1',
      '    def get_balance(self):',
      '        return self.balance + 1',
      '',
      '# ═══ SECTION 3: Transaction History ═══',
      '',
      '    # BUG: returns all transactions instead of filtered type',
      '    def get_transactions(self, type=None):',
      '        if type is None:',
      '            return self.transactions',
      '        return self.transactions',
      '',
      '    # BUG: count returns 0 always',
      '    def transaction_count(self):',
      '        return 0',
      '',
      '    # BUG: last_transaction returns first instead of last',
      '    def last_transaction(self):',
      '        if not self.transactions:',
      '            return None',
      '        return self.transactions[0]',
    ],
    tests: [
      // Section 1
      {
        name: 'validate_amount rejects negatives',
        section: 0,
      },
      {
        name: 'is_active returns False gracefully',
        section: 0,
        fix: { line: 22, hint: 'Replace raise RuntimeError(...) with return False', code: '            return False' },
        sabotageHint: { line: 22, hint: 'Change return False back to raise RuntimeError', code: '            raise RuntimeError("Account is closed")' },
      },
      {
        name: 'close_account deactivates account',
        section: 0,
        fix: { line: 26, hint: 'This one is already correct — self.active = False is there', code: '        self.active = False' },
        sabotageHint: { line: 26, hint: 'Change self.active = False to self.active = True', code: '        self.active = True' },
      },
      // Section 2
      {
        name: 'deposit adds to balance',
        section: 1,
        fix: { line: 35, hint: 'Change -= to +=', code: '        self.balance += amount' },
        sabotageHint: { line: 35, hint: 'Change += back to -=', code: '        self.balance -= amount' },
      },
      {
        name: 'withdraw checks sufficient funds',
        section: 1,
        fix: { line: 44, hint: 'Add a check before subtracting: if self.balance < amount: return False', code: '        if self.balance < amount: return False' },
        sabotageHint: { line: 44, hint: 'Remove the balance check so it always subtracts', code: '        # no check' },
      },
      {
        name: 'get_balance returns exact balance',
        section: 1,
        fix: { line: 82, hint: 'Remove the + 1', code: '        return self.balance' },
        sabotageHint: { line: 82, hint: 'Add + 1 back: return self.balance + 1', code: '        return self.balance + 1' },
      },
      // Section 3
      {
        name: 'get_transactions filters by type',
        section: 2,
        fix: { line: 89, hint: 'Replace the second `return self.transactions` with a filtered list', code: '        return [t for t in self.transactions if t[0] == type]' },
        sabotageHint: { line: 89, hint: 'Make both branches return self.transactions (no filter)', code: '        return self.transactions' },
      },
      {
        name: 'transaction_count returns correct count',
        section: 2,
        fix: { line: 93, hint: 'Replace return 0 with return len(self.transactions)', code: '        return len(self.transactions)' },
        sabotageHint: { line: 93, hint: 'Change return len(...) back to return 0', code: '        return 0' },
      },
      {
        name: 'last_transaction returns last item',
        section: 2,
        fix: { line: 100, hint: 'Change [0] to [-1] to get the last item', code: '        return self.transactions[-1]' },
        sabotageHint: { line: 100, hint: 'Change [-1] back to [0]', code: '        return self.transactions[0]' },
      },
    ],
  },

  'Data Structures & Algorithms': {
    id: 'dsa_search_sort',
    title: 'Search & Sort Library',
    language: 'python',
    description: 'A utility library with binary search, merge sort, and analysis tools.',
    impostorGoals: [
      'Change mid+1 back to mid in binary search',
      'Break the merge step in merge sort',
      'Make count_comparisons return 0',
    ],
    sections: [
      { title: 'Binary Search', startLine: 0, endLine: 28 },
      { title: 'Merge Sort', startLine: 29, endLine: 60 },
      { title: 'Analysis Tools', startLine: 61, endLine: 85 },
    ],
    code: [
      '# Search & Sort Library — Fix all bugs across 3 sections',
      '# Work together to pass all 9 tests',
      '',
      '# ═══ SECTION 1: Binary Search ═══',
      '',
      '# BUG: right should be len(arr) - 1',
      'def binary_search(arr, target):',
      '    left, right = 0, len(arr)',
      '    while left <= right:',
      '        mid = (left + right) // 2',
      '        if arr[mid] == target:',
      '            return mid',
      '        elif arr[mid] < target:',
      '            # BUG: should be mid + 1',
      '            left = mid',
      '        else:',
      '            # BUG: should be mid - 1',
      '            right = mid',
      '    return -1',
      '',
      '# BUG: should search all elements, not arr[1:]',
      'def search_all(arr, target):',
      '    results = []',
      '    for i, val in enumerate(arr[1:]):',
      '        if val == target:',
      '            results.append(i)',
      '    return results',
      '',
      '# ═══ SECTION 2: Merge Sort ═══',
      '',
      'def merge_sort(arr):',
      '    if len(arr) <= 1:',
      '        return arr',
      '    mid = len(arr) // 2',
      '    left  = merge_sort(arr[:mid])',
      '    right = merge_sort(arr[mid:])',
      '    return merge(left, right)',
      '',
      'def merge(left, right):',
      '    result = []',
      '    i = j = 0',
      '    while i < len(left) and j < len(right):',
      '        # BUG: should be <=, not <',
      '        if left[i] < right[j]:',
      '            result.append(left[i])',
      '            i += 1',
      '        else:',
      '            result.append(right[j])',
      '            j += 1',
      '    # BUG: missing remainder — should extend with both leftovers',
      '    result.extend(left[i:])',
      '    return result',
      '',
      '# ═══ SECTION 3: Analysis Tools ═══',
      '',
      '# BUG: always returns 0',
      'def count_comparisons(arr, target):',
      '    count = 0',
      '    for item in arr:',
      '        count += 1',
      '        if item == target:',
      '            break',
      '    return 0',
      '',
      '# BUG: is_sorted checks wrong direction',
      'def is_sorted(arr, ascending=True):',
      '    for i in range(len(arr) - 1):',
      '        if ascending and arr[i] > arr[i + 1]:',
      '            return False',
      '        if not ascending and arr[i] < arr[i + 1]:',
      '            return False',
      '    return True',
      '',
      '# BUG: returns minimum instead of maximum',
      'def find_max(arr):',
      '    if not arr:',
      '        return None',
      '    return min(arr)',
    ],
    tests: [
      {
        name: 'binary_search right boundary correct',
        section: 0,
      },
      {
        name: 'binary_search pointers advance correctly',
        section: 0,
      },
      {
        name: 'search_all searches from index 0',
        section: 0,
      },
      {
        name: 'merge_sort comparison uses <=',
        section: 1,
      },
      {
        name: 'merge includes both remainders',
        section: 1,
      },
      {
        name: 'merge_sort returns sorted array',
        section: 1,
      },
      {
        name: 'count_comparisons returns count not 0',
        section: 2,
      },
      {
        name: 'is_sorted correctly checks order',
        section: 2,
      },
      {
        name: 'find_max returns maximum not minimum',
        section: 2,
      },
    ],
  },

  'Security': {
    id: 'sec_auth_system',
    title: 'Auth & Permission System',
    language: 'python',
    description: 'A complete authentication and permission management system.',
    impostorGoals: [
      'Make password hashing use md5 instead of sha256',
      'Make token validation always return True',
      'Remove the admin check from has_permission',
    ],
    sections: [
      { title: 'Password & Hashing', startLine: 0, endLine: 28 },
      { title: 'Token Management', startLine: 29, endLine: 55 },
      { title: 'Permission System', startLine: 56, endLine: 80 },
    ],
    code: [
      '# Auth & Permission System — Fix all bugs across 3 sections',
      '# Work together to pass all 9 tests',
      '',
      '# ═══ SECTION 1: Password & Hashing ═══',
      '',
      'import hashlib, secrets, time',
      '',
      '# BUG: uses md5 instead of sha256',
      'def hash_password(password, salt=None):',
      '    if salt is None:',
      '        salt = secrets.token_hex(16)',
      '    hashed = hashlib.md5((password + salt).encode()).hexdigest()',
      '    return f"{salt}:{hashed}"',
      '',
      '# BUG: always returns True',
      'def verify_password(password, stored_hash):',
      '    salt, _ = stored_hash.split(":")',
      '    return True',
      '',
      '# BUG: min length is 4, should be 8',
      'def is_strong_password(password):',
      '    if len(password) < 4:',
      '        return False',
      '    has_upper = any(c.isupper() for c in password)',
      '    has_digit = any(c.isdigit() for c in password)',
      '    return has_upper and has_digit',
      '',
      '# ═══ SECTION 2: Token Management ═══',
      '',
      'tokens = {}',
      '',
      '# BUG: expiry is 0 seconds (should be 3600)',
      'def create_token(user_id):',
      '    token = secrets.token_hex(32)',
      '    tokens[token] = {',
      '        "user_id": user_id,',
      '        "expires": time.time() + 0',
      '    }',
      '    return token',
      '',
      '# BUG: does not check expiry',
      'def validate_token(token):',
      '    if token not in tokens:',
      '        return None',
      '    return tokens[token]["user_id"]',
      '',
      '# BUG: does not delete from tokens dict',
      'def revoke_token(token):',
      '    if token in tokens:',
      '        pass',
      '',
      '# ═══ SECTION 3: Permission System ═══',
      '',
      'user_roles = {}',
      '',
      'def assign_role(user_id, role):',
      '    user_roles[user_id] = role',
      '',
      '# BUG: admin always gets False',
      'def has_permission(user_id, permission):',
      '    role = user_roles.get(user_id, "guest")',
      '    permissions = {',
      '        "admin":  [],',
      '        "editor": ["read", "write"],',
      '        "viewer": ["read"],',
      '        "guest":  []',
      '    }',
      '    return permission in permissions.get(role, [])',
      '',
      '# BUG: returns opposite — should return True if admin',
      'def is_admin(user_id):',
      '    return user_roles.get(user_id) != "admin"',
      '',
      '# BUG: allows empty permission string',
      'def validate_permission_name(name):',
      '    return isinstance(name, str)',
    ],
    tests: [
      {
        name: 'hash_password uses sha256',
        section: 0,
      },
      {
        name: 'verify_password checks the hash',
        section: 0,
      },
      {
        name: 'is_strong_password requires length 8',
        section: 0,
      },
      {
        name: 'create_token sets 1 hour expiry',
        section: 1,
      },
      {
        name: 'validate_token checks expiry',
        section: 1,
      },
      {
        name: 'revoke_token removes from tokens',
        section: 1,
      },
      {
        name: 'has_permission grants admin all rights',
        section: 2,
      },
      {
        name: 'is_admin returns True for admins',
        section: 2,
      },
      {
        name: 'validate_permission_name rejects empty string',
        section: 2,
      },
    ],
  },

  'Front-End': {
    id: 'fe_component_system',
    title: 'UI Component System',
    language: 'javascript',
    description: 'A component system with state management, routing, and DOM utilities.',
    impostorGoals: [
      'Make setState replace state instead of merging',
      'Make navigate not update the current route',
      'Break the event listener cleanup',
    ],
    sections: [
      { title: 'State Management', startLine: 0, endLine: 30 },
      { title: 'Router', startLine: 31, endLine: 58 },
      { title: 'DOM Utilities', startLine: 59, endLine: 85 },
    ],
    code: [
      '// UI Component System — Fix all bugs across 3 sections',
      '// Work together to pass all 9 tests',
      '',
      '// ═══ SECTION 1: State Management ═══',
      '',
      'class Store {',
      '  constructor(initial) {',
      '    this.state = initial;',
      '    this.listeners = [];',
      '    this.history = [];',
      '  }',
      '',
      '  // BUG: replaces state instead of merging',
      '  setState(patch) {',
      '    this.history.push(this.state);',
      '    this.state = patch;',
      '    this.listeners.forEach(fn => fn(this.state));',
      '  }',
      '',
      '  // BUG: returns undefined',
      '  getState() {',
      '    return undefined;',
      '  }',
      '',
      '  // BUG: never removes listener on unsubscribe',
      '  subscribe(fn) {',
      '    this.listeners.push(fn);',
      '    return () => {};',
      '  }',
      '',
      '  // BUG: undo does nothing',
      '  undo() {',
      '    if (this.history.length === 0) return;',
      '    const prev = this.history.pop();',
      '  }',
      '',
      '// ═══ SECTION 2: Router ═══',
      '',
      'class Router {',
      '  constructor() {',
      '    this.routes = {};',
      '    this.current = "/";',
      '    this.beforeEach = null;',
      '  }',
      '',
      '  // BUG: does not save the route handler',
      '  register(path, handler) {',
      '    // missing',
      '  }',
      '',
      '  // BUG: does not update this.current',
      '  navigate(path) {',
      '    if (this.beforeEach) this.beforeEach(path);',
      '    const handler = this.routes[path];',
      '    if (handler) handler();',
      '  }',
      '',
      '  // BUG: returns null',
      '  getCurrent() {',
      '    return null;',
      '  }',
      '',
      '  use(middleware) {',
      '    this.beforeEach = middleware;',
      '  }',
      '',
      '// ═══ SECTION 3: DOM Utilities ═══',
      '',
      'class DOMUtils {',
      '  // BUG: returns null instead of creating element',
      '  createElement(tag, attrs = {}, text = "") {',
      '    return null;',
      '  }',
      '',
      '  // BUG: does nothing',
      '  addClass(el, ...classes) {',
      '    // missing',
      '  }',
      '',
      '  // BUG: never removes old listener before adding new one',
      '  on(el, event, handler) {',
      '    el.addEventListener(event, handler);',
      '  }',
      '',
      '  // BUG: sets property incorrectly',
      '  setStyle(el, prop, val) {',
      '    el.style = val;',
      '  }',
      '',
      '  // BUG: returns innerHTML not textContent',
      '  getText(el) {',
      '    return el.innerHTML;',
      '  }',
      '}',
    ],
    tests: [
      {
        name: 'setState merges state',
        section: 0,
      },
      {
        name: 'getState returns this.state',
        section: 0,
      },
      {
        name: 'subscribe returns working unsubscribe',
        section: 0,
      },
      {
        name: 'register saves route handler',
        section: 1,
      },
      {
        name: 'navigate updates current path',
        section: 1,
      },
      {
        name: 'getCurrent returns current route',
        section: 1,
      },
      {
        name: 'createElement creates real element',
        section: 2,
      },
      {
        name: 'addClass uses classList',
        section: 2,
      },
      {
        name: 'setStyle sets individual property',
        section: 2,
      },
    ],
  },

  'Back-End': {
    id: 'be_api_server',
    title: 'REST API Server',
    language: 'javascript',
    description: 'An Express-style API server with middleware, routing, and caching.',
    impostorGoals: [
      'Remove next() from the logger middleware',
      'Make the cache always return undefined',
      'Make the rate limiter always allow requests',
    ],
    sections: [
      { title: 'Middleware Pipeline', startLine: 0, endLine: 30 },
      { title: 'Route Handler', startLine: 31, endLine: 58 },
      { title: 'Cache & Rate Limit', startLine: 59, endLine: 85 },
    ],
    code: [
      '// REST API Server — Fix all bugs across 3 sections',
      '// Work together to pass all 9 tests',
      '',
      '// ═══ SECTION 1: Middleware Pipeline ═══',
      '',
      '// BUG: never calls next()',
      'const logger = (req, res, next) => {',
      '  const timestamp = new Date().toISOString();',
      '  console.log(`[${timestamp}] ${req.method} ${req.url}`);',
      '};',
      '',
      '// BUG: blocks valid tokens',
      'const auth = (req, res, next) => {',
      '  const token = req.headers.authorization?.replace("Bearer ", "");',
      '  if (!token) {',
      '    return res.status(401).json({ error: "No token" });',
      '  }',
      '  res.status(403).json({ error: "Forbidden" });',
      '};',
      '',
      '// BUG: does not send error response',
      'const errorHandler = (err, req, res, next) => {',
      '  console.error(err.stack);',
      '};',
      '',
      '// BUG: does not attach parsed body to req',
      'const jsonParser = (req, res, next) => {',
      '  let body = "";',
      '  req.on("data", chunk => { body += chunk; });',
      '  req.on("end", () => {',
      '    next();',
      '  });',
      '};',
      '',
      '// ═══ SECTION 2: Route Handler ═══',
      '',
      'class Router {',
      '  constructor() {',
      '    this.routes = {};',
      '  }',
      '',
      '  // BUG: key should be `${method}:${path}`, uses only path',
      '  register(method, path, handler) {',
      '    this.routes[path] = handler;',
      '  }',
      '',
      '  // BUG: does not pass params to handler',
      '  handle(req, res) {',
      '    const key = `${req.method}:${req.path}`;',
      '    const handler = this.routes[key];',
      '    if (!handler) {',
      '      return res.status(404).json({ error: "Not found" });',
      '    }',
      '    handler(req, res);',
      '  }',
      '',
      '  // BUG: params extracted wrong (off by one)',
      '  extractParams(pattern, path) {',
      '    const keys = (pattern.match(/:[a-z]+/g) || []).map(k => k.slice(2));',
      '    const values = path.split("/").slice(2);',
      '    return Object.fromEntries(keys.map((k, i) => [k, values[i]]));',
      '  }',
      '}',
      '',
      '// ═══ SECTION 3: Cache & Rate Limit ═══',
      '',
      'class Cache {',
      '  constructor(ttl = 60) {',
      '    this.store = {};',
      '    this.ttl = ttl;',
      '  }',
      '',
      '  // BUG: stores entry but get always returns undefined',
      '  set(key, value) {',
      '    this.store[key] = { value, expires: Date.now() + this.ttl * 1000 };',
      '  }',
      '',
      '  get(key) {',
      '    const entry = this.store[key];',
      '    if (!entry || Date.now() > entry.expires) return undefined;',
      '    return undefined;',
      '  }',
      '',
      '  // BUG: always returns true even when rate exceeded',
      '  isRateLimited(ip, maxReq = 10) {',
      '    if (!this.store[ip]) this.store[ip] = { count: 0, expires: Date.now() + 60000 };',
      '    this.store[ip].count++;',
      '    return true;',
      '  }',
      '',
      '  // BUG: does not delete expired entries',
      '  cleanup() {',
      '    const now = Date.now();',
      '  }',
      '}',
    ],
    tests: [
      {
        name: 'logger calls next()',
        section: 0,
      },
      {
        name: 'auth allows valid tokens',
        section: 0,
      },
      {
        name: 'errorHandler sends error response',
        section: 0,
      },
      {
        name: 'register uses method+path as key',
        section: 1,
      },
      {
        name: 'handle passes params to handler',
        section: 1,
      },
      {
        name: 'extractParams slices from index 1',
        section: 1,
      },
      {
        name: 'cache get returns stored value',
        section: 2,
      },
      {
        name: 'isRateLimited blocks when over limit',
        section: 2,
      },
      {
        name: 'cleanup removes expired entries',
        section: 2,
      },
    ],
  },
  'Event System': {
    id: 'event_system',
    title: 'Event Bus',
    language: 'python',
    description: 'A pub/sub event bus with priorities, history, and replay.',
    impostorGoals: [
      'Make once() fire every time instead of once',
      'Break priority ordering (reverse or ignore it)',
      'Make replay() emit to wrong event or skip history',
    ],
    sections: [
      { title: 'Subscribe & Emit', startLine: 0, endLine: 28 },
      { title: 'Priority & Once', startLine: 29, endLine: 56 },
      { title: 'History & Replay', startLine: 57, endLine: 84 },
    ],
    code: [
      '# Event Bus — Fix all bugs across 3 sections',
      '# Work together to pass all 9 tests',
      '',
      '# ═══ SECTION 1: Subscribe & Emit ═══',
      '',
      'class EventBus:',
      '    def __init__(self):',
      '        self.listeners = {}     # event -> list of {fn, priority, once}',
      '        self._history  = {}     # event -> list of arg tuples',
      '',
      '    # BUG: appends to wrong key — uses list() instead of event',
      '    def subscribe(self, event, fn, priority=0):',
      '        if event not in self.listeners:',
      '            self.listeners[event] = []',
      '        self.listeners[event].append({\'fn\': fn, \'priority\': priority, \'once\': False})',
      '',
      '    # BUG: checks wrong condition — removes nothing when fn matches',
      '    def unsubscribe(self, event, fn):',
      '        if event in self.listeners:',
      '            self.listeners[event] = [l for l in self.listeners[event] if l[\'fn\'] == fn]',
      '',
      '    # BUG: calls fn() without passing *args',
      '    def emit(self, event, *args):',
      '        if event not in self.listeners:',
      '            return',
      "        if event not in self._history:",
      "            self._history[event] = []",
      "        self._history[event].append(args)",
      '        keep = []',
      '        for listener in self.listeners[event]:',
      '            listener[\'fn\']()',
      '            if not listener[\'once\']:',
      '                keep.append(listener)',
      '        self.listeners[event] = keep',
      '',
      '# ═══ SECTION 2: Priority & Once ═══',
      '',
      '    # BUG: registers once=False instead of True',
      '    def once(self, event, fn, priority=0):',
      '        if event not in self.listeners:',
      '            self.listeners[event] = []',
      '        self.listeners[event].append({\'fn\': fn, \'priority\': priority, \'once\': False})',
      '',
      '    # BUG: listeners are sorted ascending (low first) instead of descending',
      '    def _sorted_listeners(self, event):',
      '        return sorted(self.listeners.get(event, []), key=lambda l: l[\'priority\'])',
      '',
      '    def can_transition(self, event):',
      '        return event in self.listeners and len(self.listeners[event]) > 0',
      '',
      '    def get_listeners(self, event):',
      '        return self._sorted_listeners(event)',
      '',
      '# ═══ SECTION 3: History & Replay ═══',
      '',
      '    # BUG: returns empty list — ignores self._history',
      '    def get_history(self, event):',
      '        return []',
      '',
      '    # BUG: replays wrong event (uses first key instead of event)',
      '    def replay(self, event):',
      '        if event not in self._history:',
      '            return',
      '        wrong_key = list(self._history.keys())[0]',
      '        for args in self._history[wrong_key]:',
      '            self.emit(event, *args)',
      '',
      '    def clear_history(self, event=None):',
      '        if event:',
      '            self._history.pop(event, None)',
      '        else:',
      '            self._history = {}',
    ],
    tests: [
      { name: 'subscribe adds listener', section: 0,
        fix: { line: 14, hint: 'The append goes to self.listeners[event], not wrong key', code: "        self.listeners[event].append({'fn': fn, 'priority': priority, 'once': False})" },
        sabotage: { line: 14, hint: 'Change self.listeners[event] to wrong key', code: "        self.listeners['_wrong'].append({'fn': fn, 'priority': priority, 'once': False})" },
      },
      { name: 'unsubscribe removes listener', section: 0,
        fix: { line: 19, hint: "Filter out where fn matches — keep where l['fn'] != fn", code: "            self.listeners[event] = [l for l in self.listeners[event] if l['fn'] != fn]" },
        sabotage: { line: 19, hint: "Change != to == so it removes everything except fn", code: "            self.listeners[event] = [l for l in self.listeners[event] if l['fn'] == fn]" },
      },
      { name: 'emit calls all listeners', section: 0,
        fix: { line: 30, hint: "Call listener['fn'](*args) not listener['fn']()", code: "            listener['fn'](*args)" },
        sabotage: { line: 30, hint: "Remove *args so fn is called with no arguments", code: "            listener['fn']()" },
      },
      { name: 'once fires only one time', section: 1,
        fix: { line: 36, hint: "Set 'once': True not False", code: "        self.listeners[event].append({'fn': fn, 'priority': priority, 'once': True})" },
        sabotage: { line: 36, hint: "Set 'once': False so it fires every time", code: "        self.listeners[event].append({'fn': fn, 'priority': priority, 'once': False})" },
      },
      { name: 'emit passes args to listeners', section: 0,
        fix: { line: 30, hint: "Pass *args: listener['fn'](*args)", code: "            listener['fn'](*args)" },
        sabotage: { line: 30, hint: "Drop args entirely", code: "            listener['fn']()" },
      },
      { name: 'priority orders listeners high-first', section: 1,
        fix: { line: 40, hint: 'Sort descending: reverse=True', code: "        return sorted(self.listeners.get(event, []), key=lambda l: l['priority'], reverse=True)" },
        sabotage: { line: 40, hint: 'Sort ascending so low priority fires first', code: "        return sorted(self.listeners.get(event, []), key=lambda l: l['priority'])" },
      },
      { name: 'namespace isolates events', section: 0,
        fix: { line: 14, hint: 'subscribe uses the event name as key — already correct if unsubscribe is fixed', code: "        self.listeners[event].append({'fn': fn, 'priority': priority, 'once': False})" },
        sabotage: { line: 14, hint: 'Store all listeners under one key so namespaces bleed', code: "        self.listeners['all'].append({'fn': fn, 'priority': priority, 'once': False})" },
      },
      { name: 'history records emitted events', section: 2,
        fix: { line: 61, hint: 'Return actual history: self._history.get(event, [])', code: '        return self._history.get(event, [])' },
        sabotage: { line: 61, hint: 'Return empty list', code: '        return []' },
      },
      { name: 'replay re-emits history to new subscriber', section: 2,
        fix: { line: 65, hint: 'Replay the correct event — use event, not wrong_key', code: '        for args in self._history[event]:' },
        sabotage: { line: 65, hint: 'Use wrong_key so wrong history is replayed', code: '        for args in self._history[wrong_key]:' },
      },
    ],
  },

  'Caching & Memory': {
    id: 'lru_cache',
    title: 'LRU Cache',
    language: 'python',
    description: 'An LRU cache with get, put, eviction, and clear.',
    impostorGoals: [
      'Break eviction to remove newest instead of oldest',
      'Make get not update recency so wrong item gets evicted',
      'Make clear only empty part of the cache',
    ],
    sections: [
      { title: 'Get & Miss', startLine: 0, endLine: 26 },
      { title: 'Put & Eviction', startLine: 27, endLine: 56 },
      { title: 'Update & Clear', startLine: 57, endLine: 80 },
    ],
    code: [
      '# LRU Cache — Fix all bugs across 3 sections',
      '# Work together to pass all 9 tests',
      '',
      '# ═══ SECTION 1: Get & Miss ═══',
      '',
      'from collections import OrderedDict',
      '',
      'class LRUCache:',
      '    def __init__(self, capacity):',
      '        self.capacity = capacity',
      '        self.cache = OrderedDict()',
      '',
      '    # BUG: returns None for missing key instead of -1',
      '    def get(self, key):',
      '        if key not in self.cache:',
      '            return None',
      '        # BUG: does not move to end (no recency update)',
      '        return self.cache[key]',
      '',
      '    def __len__(self):',
      '        return len(self.cache)',
      '',
      '    def __contains__(self, key):',
      '        return key in self.cache',
      '',
      '    def peek(self, key):',
      '        return self.cache.get(key, -1)',
      '',
      '# ═══ SECTION 2: Put & Eviction ═══',
      '',
      '    # BUG: evicts most-recently-used (last) instead of least-recently-used (first)',
      '    def put(self, key, value):',
      '        if key in self.cache:',
      '            self.cache.move_to_end(key)',
      '        self.cache[key] = value',
      '        if len(self.cache) > self.capacity:',
      '            self.cache.popitem(last=True)',
      '',
      '    def keys(self):',
      '        return list(self.cache.keys())',
      '',
      '    def values(self):',
      '        return list(self.cache.values())',
      '',
      '    def items(self):',
      '        return list(self.cache.items())',
      '',
      '    def capacity_remaining(self):',
      '        return self.capacity - len(self.cache)',
      '',
      '    def is_full(self):',
      '        return len(self.cache) >= self.capacity',
      '',
      '# ═══ SECTION 3: Update & Clear ═══',
      '',
      '    # BUG: does not move updated key to end (still LRU after update)',
      '    def update(self, key, value):',
      '        if key in self.cache:',
      '            self.cache[key] = value',
      '        else:',
      '            self.put(key, value)',
      '',
      '    # BUG: only pops one item instead of clearing all',
      '    def clear(self):',
      '        self.cache.popitem()',
      '',
      '    def get_order(self, ):',
      '        return list(self.cache.keys())',
      '',
      '    def resize(self, new_capacity):',
      '        self.capacity = new_capacity',
      '        while len(self.cache) > self.capacity:',
      '            self.cache.popitem(last=False)',
    ],
    tests: [
      { name: 'put stores value by key', section: 0,
        fix: { line: 33, hint: 'put is correct if eviction is also fixed (last=False)', code: '            self.cache.popitem(last=False)' },
        sabotage: { line: 33, hint: 'Change last=False to last=True to evict newest', code: '            self.cache.popitem(last=True)' },
      },
      { name: 'get retrieves correct value', section: 0,
        fix: { line: 15, hint: 'Return -1 for missing key, not None', code: '            return -1' },
        sabotage: { line: 15, hint: 'Return None so equality checks against -1 fail', code: '            return None' },
      },
      { name: 'get returns -1 for missing key', section: 0,
        fix: { line: 15, hint: 'Change return None to return -1', code: '            return -1' },
        sabotage: { line: 15, hint: 'Return None or 0 for missing key', code: '            return None' },
      },
      { name: 'capacity evicts LRU on overflow', section: 1,
        fix: { line: 33, hint: 'Evict from front (LRU): popitem(last=False)', code: '            self.cache.popitem(last=False)' },
        sabotage: { line: 33, hint: 'Evict from back (MRU): popitem(last=True)', code: '            self.cache.popitem(last=True)' },
      },
      { name: 'get updates recency on hit', section: 0,
        fix: { line: 17, hint: 'Add self.cache.move_to_end(key) before returning', code: '        self.cache.move_to_end(key)\n        return self.cache[key]' },
        sabotage: { line: 17, hint: 'Remove the move_to_end call', code: '        return self.cache[key]' },
      },
      { name: 'put updates existing key in-place', section: 1,
        fix: { line: 29, hint: 'put already moves to end on existing key — just fix eviction direction', code: '            self.cache.popitem(last=False)' },
        sabotage: { line: 29, hint: 'On existing key, do NOT move to end', code: '        self.cache[key] = value' },
      },
      { name: 'eviction order is correct after gets', section: 1,
        fix: { line: 33, hint: 'Must evict LRU (first=last=False)', code: '            self.cache.popitem(last=False)' },
        sabotage: { line: 33, hint: 'Evict most recently used instead', code: '            self.cache.popitem(last=True)' },
      },
      { name: 'size does not exceed capacity', section: 1,
        fix: { line: 33, hint: 'Fix eviction so size is bounded', code: '            self.cache.popitem(last=False)' },
        sabotage: { line: 32, hint: 'Change > to >= so eviction never fires', code: '        if len(self.cache) >= self.capacity + 1:' },
      },
      { name: 'clear resets the cache', section: 2,
        fix: { line: 62, hint: 'Use self.cache.clear() to remove everything', code: '        self.cache.clear()' },
        sabotage: { line: 62, hint: 'Only pop one item', code: '        self.cache.popitem()' },
      },
    ],
  },

  'State Machines': {
    id: 'state_machine',
    title: 'Finite State Machine',
    language: 'python',
    description: 'A generic FSM with transitions, guards, callbacks, and history.',
    impostorGoals: [
      'Make invalid transitions succeed silently',
      'Break guard so it always passes',
      'Make history record wrong from-state',
    ],
    sections: [
      { title: 'Transitions & Guards', startLine: 0, endLine: 30 },
      { title: 'Callbacks & Events', startLine: 31, endLine: 60 },
      { title: 'History & Reset', startLine: 61, endLine: 84 },
    ],
    code: [
      '# Finite State Machine — Fix all bugs across 3 sections',
      '# Work together to pass all 9 tests',
      '',
      '# ═══ SECTION 1: Transitions & Guards ═══',
      '',
      'class StateMachine:',
      '    def __init__(self, initial):',
      '        self.initial  = initial',
      '        self.state    = initial',
      '        self._transitions = {}   # (from, event) -> {to, guard}',
      '        self._on_enter = {}      # state -> list of callbacks',
      '        self._on_exit  = {}      # state -> list of callbacks',
      '        self.history   = []      # list of (from, event, to) triples',
      '',
      '    def add_transition(self, from_state, event, to_state, guard=None):',
      '        self._transitions[(from_state, event)] = {\'to\': to_state, \'guard\': guard}',
      '',
      '    # BUG: does not raise on invalid transition — silently ignores it',
      '    def transition(self, event):',
      '        key = (self.state, event)',
      '        if key not in self._transitions:',
      '            return   # should raise ValueError',
      '        t = self._transitions[key]',
      '        guard = t.get(\'guard\')',
      '        # BUG: negates guard — blocks when guard returns True)',
      '        if guard and guard():',
      '            raise ValueError(f"Guard blocked transition \'{event}\'")',
      '        prev = self.state',
      '        self._fire_exit(prev)',
      '        self.state = t[\'to\']',
      '        self._fire_enter(self.state)',
      '        self.history.append((prev, event, self.state))',
      '',
      '# ═══ SECTION 2: Callbacks & Events ═══',
      '',
      '    def on_enter(self, state, fn):',
      '        self._on_enter.setdefault(state, []).append(fn)',
      '',
      '    def on_exit(self, state, fn):',
      '        self._on_exit.setdefault(state, []).append(fn)',
      '',
      '    def _fire_enter(self, state):',
      '        for fn in self._on_enter.get(state, []):',
      '            fn()',
      '',
      '    def _fire_exit(self, state):',
      '        for fn in self._on_exit.get(state, []):',
      '            fn()',
      '',
      '    # BUG: returns True always (ignores whether transition exists)',
      '    def can_transition(self, event):',
      '        return True',
      '',
      '    def get_available_events(self):',
      '        return [e for (s, e) in self._transitions if s == self.state]',
      '',
      '    def get_state(self):',
      '        return self.state',
      '',
      '# ═══ SECTION 3: History & Reset ═══',
      '',
      '    # BUG: appends wrong values to history (records to→from instead of from→to)',
      '    #     Already fixed in __init__ approach; the history.append is correct above',
      '    #     but the history is cleared on reset incorrectly:',
      '',
      '    # BUG: reset sets state to last history entry instead of self.initial',
      '    def reset(self):',
      '        if self.history:',
      '            self.state = self.history[-1][2]   # wrong: last \'to\' state',
      '        else:',
      '            self.state = self.initial',
      '        self.history = []',
      '',
      '    def history_length(self):',
      '        return len(self.history)',
      '',
      '    def last_event(self):',
      '        return self.history[-1][1] if self.history else None',
    ],
    tests: [
      { name: 'initial state is set correctly', section: 0,
        fix: { line: 8, hint: 'self.state = initial is already correct — just ensure it is set', code: '        self.state    = initial' },
        sabotage: { line: 8, hint: "Set self.state to None at init", code: '        self.state    = None' },
      },
      { name: 'valid transition changes state', section: 0,
        fix: { line: 21, hint: "Raise ValueError when key not found instead of returning", code: "            raise ValueError(f\"No transition '{event}' from '{self.state}'\")" },
        sabotage: { line: 21, hint: "Return silently on invalid transition", code: '            return' },
      },
      { name: 'invalid transition raises error', section: 0,
        fix: { line: 21, hint: 'Add raise ValueError when key not in transitions', code: "            raise ValueError(f\"No transition '{event}' from '{self.state}'\")" },
        sabotage: { line: 21, hint: 'Return silently so invalid transitions go unnoticed', code: '            return' },
      },
      { name: 'guard condition blocks transition', section: 0,
        fix: { line: 24, hint: "Guard blocks when it returns False, not True — use 'if guard and not guard()'", code: '        if guard and not guard():' },
        sabotage: { line: 24, hint: "Flip guard check: block when guard() is True instead of False", code: '        if guard and guard():' },
      },
      { name: 'on_enter callback fires on entry', section: 1,
        fix: { line: 29, hint: 'on_enter/on_exit are correct — ensure transition is fixed first', code: '        self.history.append((prev, event, self.state))' },
        sabotage: { line: 40, hint: 'Clear on_enter callbacks before firing them', code: '        self._on_enter[state] = []' },
      },
      { name: 'on_exit callback fires on exit', section: 1,
        fix: { line: 43, hint: '_fire_exit is correct — fix the transition method to call it', code: '        self._fire_exit(prev)' },
        sabotage: { line: 43, hint: 'Clear on_exit before firing so callbacks never run', code: '        self._on_exit[state] = []' },
      },
      { name: 'history tracks all transitions', section: 2,
        fix: { line: 30, hint: 'history.append already correct — fix the invalid transition guard so history is populated', code: '        self.history.append((prev, event, self.state))' },
        sabotage: { line: 30, hint: 'Record wrong state — swap prev and self.state', code: '        self.history.append((self.state, event, prev))' },
      },
      { name: 'can_transition returns correct bool', section: 1,
        fix: { line: 50, hint: "Return (self.state, event) in self._transitions", code: '        return (self.state, event) in self._transitions' },
        sabotage: { line: 50, hint: 'Always return True', code: '        return True' },
      },
      { name: 'reset returns to initial state', section: 2,
        fix: { line: 64, hint: "Set self.state = self.initial, not last history entry", code: '        self.state = self.initial' },
        sabotage: { line: 64, hint: 'Set to last visited state instead of initial', code: '        self.state = self.history[-1][2]' },
      },
    ],
  },

  'Graph Algorithms': {
    id: 'graph_traversal',
    title: 'Graph Traversal',
    language: 'python',
    description: 'A directed graph with BFS, DFS, cycle detection, and shortest path.',
    impostorGoals: [
      'Break BFS to do DFS ordering',
      'Make has_path always return True',
      'Break cycle detection to miss cycles',
    ],
    sections: [
      { title: 'Graph & BFS', startLine: 0, endLine: 30 },
      { title: 'DFS & Path Finding', startLine: 31, endLine: 58 },
      { title: 'Cycle Detection & Shortest Path', startLine: 59, endLine: 84 },
    ],
    code: [
      '# Graph Traversal — Fix all bugs across 3 sections',
      '# Work together to pass all 9 tests',
      '',
      '# ═══ SECTION 1: Graph & BFS ═══',
      '',
      'from collections import deque, defaultdict',
      '',
      'class Graph:',
      '    def __init__(self):',
      '        self.adjacency = defaultdict(list)',
      '',
      '    def add_edge(self, u, v):',
      '        self.adjacency[u].append(v)',
      '',
      '    # BUG: uses stack (pop) instead of queue (popleft) — becomes DFS not BFS',
      '    def bfs(self, start):',
      '        visited = []',
      '        seen    = {start}',
      '        queue   = deque([start])',
      '        while queue:',
      '            node = queue.pop()   # should be popleft()',
      '            visited.append(node)',
      '            for nb in self.adjacency[node]:',
      '                if nb not in seen:',
      '                    seen.add(nb)',
      '                    queue.append(nb)',
      '        return visited',
      '',
      '    def node_count(self):',
      '        nodes = set(self.adjacency.keys())',
      '        for vs in self.adjacency.values(): nodes.update(vs)',
      '        return len(nodes)',
      '',
      '# ═══ SECTION 2: DFS & Path Finding ═══',
      '',
      '    # BUG: does not mark nodes as visited — infinite loop on cycles',
      '    def dfs(self, start):',
      '        visited = []',
      '        seen    = set()',
      '        stack   = [start]',
      '        while stack:',
      '            node = stack.pop()',
      '            if node in seen:',
      '                continue',
      '            visited.append(node)',
      '            for nb in self.adjacency[node]:',
      '                stack.append(nb)    # BUG: should only append if nb not in seen',
      '        return visited',
      '',
      '    # BUG: always returns True',
      '    def has_path(self, src, dst):',
      '        return True',
      '',
      '    def neighbors(self, node):',
      '        return list(self.adjacency[node])',
      '',
      '# ═══ SECTION 3: Cycle Detection & Shortest Path ═══',
      '',
      '    # BUG: never adds node to recursion stack so cycles are missed',
      '    def has_cycle(self):',
      '        visited   = set()',
      '        rec_stack = set()',
      '        def dfs_cycle(node):',
      '            visited.add(node)',
      '            # BUG: missing rec_stack.add(node)',
      '            for nb in self.adjacency[node]:',
      '                if nb not in visited:',
      '                    if dfs_cycle(nb): return True',
      '                elif nb in rec_stack:',
      '                    return True',
      '            rec_stack.discard(node)',
      '            return False',
      '        all_nodes = set(self.adjacency.keys())',
      '        for vs in self.adjacency.values(): all_nodes.update(vs)',
      '        for n in all_nodes:',
      '            if n not in visited:',
      '                if dfs_cycle(n): return True',
      '        return False',
      '',
      '    # BUG: returns number of nodes visited, not shortest path length',
      '    def shortest_path(self, src, dst):',
      '        visited = set([src])',
      '        queue   = deque([(src, 0)])',
      '        while queue:',
      '            node, dist = queue.popleft()',
      '            if node == dst:',
      '                return len(visited)   # should return dist',
      '            for nb in self.adjacency[node]:',
      '                if nb not in visited:',
      '                    visited.add(nb)',
      '                    queue.append((nb, dist + 1))',
      '        return -1',
    ],
    tests: [
      { name: 'add_edge creates adjacency', section: 0,
        fix: { line: 12, hint: 'add_edge is correct — self.adjacency[u].append(v)', code: '        self.adjacency[u].append(v)' },
        sabotage: { line: 12, hint: 'Append to wrong direction v→u instead of u→v', code: '        self.adjacency[v].append(u)' },
      },
      { name: 'bfs visits all nodes', section: 0,
        fix: { line: 20, hint: 'Use popleft() for BFS queue behaviour', code: '            node = queue.popleft()' },
        sabotage: { line: 20, hint: 'Use pop() to turn BFS into DFS', code: '            node = queue.pop()' },
      },
      { name: 'bfs order is level-by-level', section: 0,
        fix: { line: 20, hint: 'Change pop() to popleft() for proper BFS level order', code: '            node = queue.popleft()' },
        sabotage: { line: 20, hint: 'Use pop() so order becomes stack (depth first)', code: '            node = queue.pop()' },
      },
      { name: 'dfs visits all nodes', section: 1,
        fix: { line: 42, hint: 'Only append nb if not already seen: if nb not in seen: stack.append(nb)', code: '                if nb not in seen: stack.append(nb)' },
        sabotage: { line: 42, hint: 'Append all neighbors without checking seen', code: '                stack.append(nb)' },
      },
      { name: 'has_path finds existing path', section: 1,
        fix: { line: 46, hint: 'Implement BFS/DFS to check reachability instead of returning True', code: '        visited = set([src])\n        q = deque([src])\n        while q:\n            n = q.popleft()\n            if n == dst: return True\n            for nb in self.adjacency[n]:\n                if nb not in visited:\n                    visited.add(nb); q.append(nb)\n        return False' },
        sabotage: { line: 46, hint: 'Always return True', code: '        return True' },
      },
      { name: 'has_path returns False for no path', section: 1,
        fix: { line: 46, hint: 'Implement proper BFS returning False when dst unreachable', code: '        visited = set([src])\n        q = deque([src])\n        while q:\n            n = q.popleft()\n            if n == dst: return True\n            for nb in self.adjacency[n]:\n                if nb not in visited:\n                    visited.add(nb); q.append(nb)\n        return False' },
        sabotage: { line: 46, hint: 'Always return True hiding disconnected graph', code: '        return True' },
      },
      { name: 'cycle detection finds cycle', section: 2,
        fix: { line: 64, hint: 'Add rec_stack.add(node) at the start of dfs_cycle', code: '            rec_stack.add(node)' },
        sabotage: { line: 64, hint: 'Remove rec_stack.add so cycles are never detected', code: '            pass  # no rec_stack tracking' },
      },
      { name: 'cycle detection passes acyclic graph', section: 2,
        fix: { line: 64, hint: 'Add rec_stack.add(node) so clean graphs still return False', code: '            rec_stack.add(node)' },
        sabotage: { line: 76, hint: 'Always return True from has_cycle', code: '        return True' },
      },
      { name: 'shortest_path returns correct length', section: 2,
        fix: { line: 86, hint: 'Return dist not len(visited)', code: '                return dist' },
        sabotage: { line: 86, hint: 'Return len(visited) instead of actual distance', code: '                return len(visited)' },
      },
    ],
  },

  'Security & Permissions': {
    id: 'permission_system',
    title: 'RBAC Permission System',
    language: 'python',
    description: 'A role-based access control system with inheritance, deny lists, and superadmin.',
    impostorGoals: [
      'Make has_permission always return True',
      'Break role inheritance chain',
      'Make deny list not override grant',
    ],
    sections: [
      { title: 'Roles & Grants', startLine: 0, endLine: 28 },
      { title: 'Revoke & Deny', startLine: 29, endLine: 58 },
      { title: 'Inheritance & Superadmin', startLine: 59, endLine: 84 },
    ],
    code: [
      '# RBAC Permission System — Fix all bugs across 3 sections',
      '# Work together to pass all 9 tests',
      '',
      '# ═══ SECTION 1: Roles & Grants ═══',
      '',
      'class PermissionSystem:',
      '    def __init__(self):',
      '        self._user_roles  = {}   # user -> role',
      '        self._grants      = {}   # role -> set of perms',
      '        self._denies      = {}   # role -> set of denied perms',
      '        self._inherits    = {}   # role -> parent role',
      '',
      '    def assign_role(self, user, role):',
      '        self._user_roles[user] = role',
      '',
      '    def get_role(self, user):',
      '        return self._user_roles.get(user)',
      '',
      '    def grant(self, role, permission):',
      '        self._grants.setdefault(role, set()).add(permission)',
      '',
      '    # BUG: checks _denies instead of _grants — always returns empty list',
      '    def list_permissions(self, role):',
      '        return list(self._denies.get(role, set()))',
      '',
      '    # BUG: returns True always — no real check',
      '    def has_permission(self, user, permission):',
      '        return True',
      '',
      '# ═══ SECTION 2: Revoke & Deny ═══',
      '',
      '    # BUG: adds to grants instead of removing',
      '    def revoke(self, role, permission):',
      '        self._grants.setdefault(role, set()).add(permission)',
      '',
      '    def deny(self, role, permission):',
      '        self._denies.setdefault(role, set()).add(permission)',
      '',
      '    def _get_all_grants(self, role, _seen=None):',
      '        if _seen is None: _seen = set()',
      '        if role in _seen: return set()',
      '        _seen.add(role)',
      '        perms = set(self._grants.get(role, set()))',
      '        parent = self._inherits.get(role)',
      '        if parent:',
      '            perms |= self._get_all_grants(parent, _seen)',
      '        return perms',
      '',
      '    def _get_all_denies(self, role, _seen=None):',
      '        if _seen is None: _seen = set()',
      '        if role in _seen: return set()',
      '        _seen.add(role)',
      '        denied = set(self._denies.get(role, set()))',
      '        parent = self._inherits.get(role)',
      '        if parent:',
      '            denied |= self._get_all_denies(parent, _seen)',
      '        return denied',
      '',
      '# ═══ SECTION 3: Inheritance & Superadmin ═══',
      '',
      '    def role_inherits(self, child_role, parent_role):',
      '        self._inherits[child_role] = parent_role',
      '',
      '    # BUG: superadmin check is inverted — blocks superadmin',
      '    def _is_superadmin(self, role):',
      '        return role != \'superadmin\'',
      '',
      '    # BUG: checks deny before grant but should apply deny on top of grant',
      '    #      Also ignores inheritance and superadmin check',
      '    def check_permission(self, user, permission):',
      '        role = self._user_roles.get(user)',
      '        if not role: return False',
      '        return permission in self._grants.get(role, set())',
      '',
      '    def get_effective_permissions(self, user):',
      '        role = self._user_roles.get(user)',
      '        if not role: return set()',
      '        return self._get_all_grants(role) - self._get_all_denies(role)',
    ],
    tests: [
      { name: 'assign_role gives user a role', section: 0,
        fix: { line: 13, hint: 'assign_role is correct — self._user_roles[user] = role', code: '        self._user_roles[user] = role' },
        sabotage: { line: 13, hint: 'Store under wrong key', code: "        self._user_roles['_'] = role" },
      },
      { name: 'grant adds permission to role', section: 0,
        fix: { line: 19, hint: 'grant is correct — uses set().add(permission)', code: '        self._grants.setdefault(role, set()).add(permission)' },
        sabotage: { line: 19, hint: 'Add to denies instead of grants', code: '        self._denies.setdefault(role, set()).add(permission)' },
      },
      { name: 'has_permission returns True for granted', section: 0,
        fix: { line: 27, hint: "Implement: get role, check _get_all_grants minus _get_all_denies, handle superadmin", code: "        role = self._user_roles.get(user)\n        if not role: return False\n        if self._is_superadmin(role): return True\n        return permission in (self._get_all_grants(role) - self._get_all_denies(role))" },
        sabotage: { line: 27, hint: 'Always return True', code: '        return True' },
      },
      { name: 'has_permission returns False for missing', section: 0,
        fix: { line: 27, hint: 'Implement real check — return False when permission not in effective grants', code: "        role = self._user_roles.get(user)\n        if not role: return False\n        if self._is_superadmin(role): return True\n        return permission in (self._get_all_grants(role) - self._get_all_denies(role))" },
        sabotage: { line: 27, hint: 'Always return True so missing perms pass', code: '        return True' },
      },
      { name: 'revoke removes permission', section: 1,
        fix: { line: 32, hint: 'Use discard() to remove, not add()', code: '        self._grants.get(role, set()).discard(permission)' },
        sabotage: { line: 32, hint: 'Add permission instead of removing', code: '        self._grants.setdefault(role, set()).add(permission)' },
      },
      { name: 'role_inherits inherits parent perms', section: 2,
        fix: { line: 60, hint: 'role_inherits is correct — fix has_permission to call _get_all_grants', code: "        role = self._user_roles.get(user)\n        if not role: return False\n        if self._is_superadmin(role): return True\n        return permission in (self._get_all_grants(role) - self._get_all_denies(role))" },
        sabotage: { line: 60, hint: "Store parent under wrong direction (child=parent key)", code: '        self._inherits[parent_role] = child_role' },
      },
      { name: 'superadmin has all permissions', section: 2,
        fix: { line: 63, hint: "Return role == 'superadmin' not role != 'superadmin'", code: "        return role == 'superadmin'" },
        sabotage: { line: 63, hint: "Return role != 'superadmin' so superadmin is blocked", code: "        return role != 'superadmin'" },
      },
      { name: 'deny overrides grant', section: 1,
        fix: { line: 27, hint: 'Subtract denies from grants: _get_all_grants(role) - _get_all_denies(role)', code: "        role = self._user_roles.get(user)\n        if not role: return False\n        if self._is_superadmin(role): return True\n        return permission in (self._get_all_grants(role) - self._get_all_denies(role))" },
        sabotage: { line: 27, hint: 'Ignore denies so deny() has no effect', code: '        return True' },
      },
      { name: 'list_permissions shows role perms', section: 0,
        fix: { line: 23, hint: 'Return grants not denies: self._grants.get(role, set())', code: '        return list(self._grants.get(role, set()))' },
        sabotage: { line: 23, hint: 'Return denies so list shows wrong data', code: '        return list(self._denies.get(role, set()))' },
      },
    ],
  },

};

function getChallengeForCategory(category) {
  const categories = Object.keys(challenges);
  const defaultCategory = 'Object-Oriented Programming';

  if (category && challenges[category]) {
    return challenges[category];
  }

  // If no category or invalid category, pick a random one
  const availableChallenges = categories.filter(cat => cat !== defaultCategory);
  const randomIndex = Math.floor(Math.random() * availableChallenges.length);
  return challenges[availableChallenges[randomIndex]];
}

module.exports = { challenges, getChallengeForCategory };